customhost = "covidreport.cf1jrcs9ijpi.us-east-2.rds.amazonaws.com"
customuser = "piyushgupta"
custompass = "piyushgupta"
customdb = "covidreport"
custombucket = "addcovidreport"
customregion = "us-east-2a"
